---
# handlers file for rundeck
- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  notify:
    - restart rundeck

- name: restart rundeck
  service:
    name: rundeck
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
