---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: java-debian-stable
    image: debian:stable
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook-11.yml
  lint:
    name: ansible-lint
scenario:
  name: debian-stable
