---
galaxy_info:
  author: Robert de Bock
  role_name: java
  description: Install and configure java on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.6
  min_ansible_container_version: 0.2.0

  platforms:
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      version:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 6
        - 7
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - artful
        - bionic

  galaxy_tags:
    - alpine
    - centos
    - debian
    - fedora
    - java
    - oracle
    - openjdk
    - jre
    - jdk
    - alternatives

dependencies: []
