---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: java-ubuntu-rolling
    image: ubuntu:rolling
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook-13.yml
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-rolling
