---
# vars file for service

_service_required_packages:
  default: []
  Debian:
    - psmisc
  RedHat:
    - psmisc
  Suse:
    - psmisc

service_required_packages: "{{ _service_required_packages[ansible_os_family] | default(_service_required_packages['default']) }}"
