---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "Uu3Y95mjP9DdSu2oRjj5Wtnu+57gPwj2ZtvLv5q4JzwO/h8U6w3cRfby1VMt+0+mcw/6P6/9Whr7X3Va5R6AwbtTHTFAlcKX9wOY3CjYMHM2uAXvZLC0tYxGD0pzRlTxs30KiXJ0/fEN58E1WbNtO7rkvnMtixaVgRRl5Y0E3/+4AYztEkO5u60Ss2IS//r8rf/HeIcoKfZfUN+uyDk2zFrvtOhqSbNXBP+8z64pzqC8YQmxhzdA8R+hJmh4yInFt585tYb+HD+n1nVNX1ILQYQfiHF4R+4ILz0m6xfvRsv9gbUfctkXFKsZL8vzsi3uu4HbjiaWre90Jq8xG3ywR7Y31yTctmjQ2pilzEtDUlEDGIiIfAXbTZzWTDzYT6dRMKQ3nCag61uGYr66OeeZ254zuiW2ZT6RZhNLqrKXDhKC1FWTBaEG/s5PkQNfj8TiyP9EEvCdsU0LQBnx/2UhX25rywRRNficgsSGvFKb+qjmCw+TCbl+n1lsSZ+kxVgp+qT8d4dvG8dh8P1MjG3TmhDPFq7aTyTi/DgLTrAl+k1kas6w5crVrVtmr7PAJGfiLbGAqJ7jWDXYzC18eG0OmtDG8O2B2YSzHaJrXYSYM+qAvQfgXrXbxHStroJbL0JXMzvOBWs64CdgOnxBtXtW25Pj0M0JBGhp/g17ufVoZpo="
  email: false
