---
# handlers file for reboot
- name: 1 wait for the start of reboot
  pause:
    seconds: "{{ reboot_delay }}"

- name: 2 wait for the machine to be up
  wait_for_connection:
    delay: "{{ reboot_up_delay }}"

- name: 3 gather facts after reboot
  setup:
