---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "tkH36m5I+z6NCA0fgaNXE1JG2KPM9+o0V63OF0ASve9CmEx9gifZVc9Iuj0jF6vf9hU7fActEVXrQOuPhdata0uHztlW3ZKD1ie5K/M7Yv4GW5hvTl2aTD3L5QtArV+ZiIYDvdW63P78lLFzBBmIl9cBuNGi+W1/KmyVOlbZI0t1bfGe5AtIDOcWzPdnpC8ykqHRBTr8ya1Gq3BJkG4iVQAIqmjNChXet8DHRB4o1U6NbnhqEf7ayvVZWUh0Oww6YLpB1Wr7efLmcgEcjawkunbt7i/jhmhjWttQV74fShxWDbC1nBsIv8o0crcGtukNhF+DQRIXLy5pdC2/Fh25h3x2i92niWxqXjdjKRPsTIZ2983WKrfgTghHi9TYTsRNwsqmLnEgybY9a8mpcCS9imJSOrwdPfa1mRGziboIO9tpF7E6GPCkSjHhNkNplilybwT7gMJAbTa+s6fep7HUU5hOC7Y6w1oj3SEb1l0xJXrpSWN47QBeOQb/bMxsVZw/YthkM0KIORwk4l8pG2iyep4GWQcw2z0cHP6ZCr/Y+sq+76dEX2eFUVtcFE3vkwDHbru+u09tUFkPUEi/vwnyXHxznXq10nXyFO8Zwwx+Mlr7X3nk6ZNGLBbfYbgNjS+/3KFUj4Na9wugh0NjZeduTHoABT1eOzu7lGED/y3L+ig="
  email: false
