---
# vars file for reboot
_reboot_command:
  default: shutdown -r now {{ reboot_message }}
  Alpine: reboot

reboot_command: "{{ _reboot_command[ansible_distribution] | default(_reboot_command['default']) }}"
